// Code generated by "stringer -type ContentKind content_kind.go"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoneContentKind-0]
	_ = x[Dungeon-1]
	_ = x[Trial-2]
	_ = x[AllianceRaid-3]
	_ = x[NormalRaid-4]
}

const _ContentKind_name = "NoneContentKindDungeonTrialAllianceRaidNormalRaid"

var _ContentKind_index = [...]uint8{0, 15, 22, 27, 39, 49}

func (i ContentKind) String() string {
	if i < 0 || i >= ContentKind(len(_ContentKind_index)-1) {
		return "ContentKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContentKind_name[_ContentKind_index[i]:_ContentKind_index[i+1]]
}
