// Code generated by "stringer -type ContentDifficulty content_difficulty.go"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoneContentDifficulty-0]
	_ = x[Normal-1]
	_ = x[Hard-2]
	_ = x[Extreme-3]
	_ = x[Savage-4]
	_ = x[Ultimate-5]
}

const _ContentDifficulty_name = "NoneContentDifficultyNormalHardExtremeSavageUltimate"

var _ContentDifficulty_index = [...]uint8{0, 21, 27, 31, 38, 44, 52}

func (i ContentDifficulty) String() string {
	if i < 0 || i >= ContentDifficulty(len(_ContentDifficulty_index)-1) {
		return "ContentDifficulty(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContentDifficulty_name[_ContentDifficulty_index[i]:_ContentDifficulty_index[i+1]]
}
