// Code generated by "stringer -type ReleaseVersion release_version.go"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoneReleaseVersion-0]
	_ = x[RealmReborn-1]
	_ = x[Heavensward-2]
	_ = x[Stormblood-3]
	_ = x[Shadowbringers-4]
	_ = x[Endwalker-5]
}

const _ReleaseVersion_name = "NoneReleaseVersionRealmRebornHeavenswardStormbloodShadowbringersEndwalker"

var _ReleaseVersion_index = [...]uint8{0, 18, 29, 40, 50, 64, 73}

func (i ReleaseVersion) String() string {
	if i < 0 || i >= ReleaseVersion(len(_ReleaseVersion_index)-1) {
		return "ReleaseVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReleaseVersion_name[_ReleaseVersion_index[i]:_ReleaseVersion_index[i+1]]
}
